version: '3'

services:
  myapp:
    image: 'bitnami/codeigniter:3'
    container_name: dockerci
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    

  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
     
    volumes: 
      - db-data:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
          - 8080:80
      volumes:
          - /sessions
      environment:
        PMA_HOST: mariadb
volumes: 
  db-data:

